---
name: into-dbus-python CI

# yamllint disable-line rule:truthy
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  development_environment_checks:
    strategy:
      matrix:
        include:
          - dependencies: black python3-isort
            task: make -f Makefile fmt-travis
          - dependencies: yamllint
            task: make -f Makefile yamllint
          - dependencies: >
              bandit
              pylint
              python3-dbus
              python3-dbus-signature-pyparsing
              python3-hypothesis
            task: >
              PATH=${PATH}:/github/home/.local/bin
              PYTHONPATH=./src make -f Makefile lint
          - dependencies: >
              python3-dbus
              python3-dbus-signature-pyparsing
              python3-hypothesis
            task: PYTHONPATH=./src make -f Makefile test
          - dependencies: >
              python3-coverage
              python3-dbus
              python3-dbus-signature-pyparsing
              python3-hypothesis
            task: PYTHONPATH=./src make -f Makefile coverage
          - dependencies: python python3-build twine
            task: make -f Makefile package
    runs-on: ubuntu-latest
    container: fedora:41  # CURRENT DEVELOPMENT ENVIRONMENT
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: >
          dnf install -y
          make
          pip
          ${{ matrix.dependencies }}
      - name: Install hs-dbus-signature
        run: pip install --user hs-dbus-signature
      - name: Install pyright
        run: pip install --user pyright
      - name: ${{ matrix.task }}
        run: ${{ matrix.task }}

  lowest_environment_checks:
    strategy:
      matrix:
        include:
          - dependencies: >
              bandit
              pylint
              python3-dbus
              python3-dbus-signature-pyparsing
              python3-hypothesis
              python3-hs-dbus-signature
            task: >
              PATH=${PATH}:/github/home/.local/bin
              PYTHONPATH=./src make -f Makefile lint
          - dependencies: >
              python3-dbus
              python3-dbus-signature-pyparsing
              python3-hypothesis
              python3-hs-dbus-signature
            task: PYTHONPATH=./src make -f Makefile test
          - dependencies: >
              python3-setuptools
              python3-dbus
              python3-dbus-signature-pyparsing
              python3-hypothesis
              python3-hs-dbus-signature
            task: make legacy-package
    runs-on: ubuntu-latest
    container: fedora:35  # LOWEST DEVELOPMENT ENVIRONMENT
    steps:
      - name: Display Python version
        run: python3 --version
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: >
          dnf install -y
          make
          pip
          ${{ matrix.dependencies }}
      - name: Install pyright
        run: pip install --user pyright
      - name: ${{ matrix.task }}
        run: ${{ matrix.task }}
